// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.8.0
// source: a_proto.proto

package a_protopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ARequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParamA string `protobuf:"bytes,1,opt,name=param_a,json=paramA,proto3" json:"param_a,omitempty"`
	ParamB int64  `protobuf:"varint,2,opt,name=param_b,json=paramB,proto3" json:"param_b,omitempty"`
}

func (x *ARequest) Reset() {
	*x = ARequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_a_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ARequest) ProtoMessage() {}

func (x *ARequest) ProtoReflect() protoreflect.Message {
	mi := &file_a_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ARequest.ProtoReflect.Descriptor instead.
func (*ARequest) Descriptor() ([]byte, []int) {
	return file_a_proto_proto_rawDescGZIP(), []int{0}
}

func (x *ARequest) GetParamA() string {
	if x != nil {
		return x.ParamA
	}
	return ""
}

func (x *ARequest) GetParamB() int64 {
	if x != nil {
		return x.ParamB
	}
	return 0
}

type AResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResA string `protobuf:"bytes,1,opt,name=res_a,json=resA,proto3" json:"res_a,omitempty"`
	ResB int64  `protobuf:"varint,2,opt,name=res_b,json=resB,proto3" json:"res_b,omitempty"`
}

func (x *AResponse) Reset() {
	*x = AResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_a_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AResponse) ProtoMessage() {}

func (x *AResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AResponse.ProtoReflect.Descriptor instead.
func (*AResponse) Descriptor() ([]byte, []int) {
	return file_a_proto_proto_rawDescGZIP(), []int{1}
}

func (x *AResponse) GetResA() string {
	if x != nil {
		return x.ResA
	}
	return ""
}

func (x *AResponse) GetResB() int64 {
	if x != nil {
		return x.ResB
	}
	return 0
}

var File_a_proto_proto protoreflect.FileDescriptor

var file_a_proto_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x70, 0x62, 0x22, 0x3d, 0x0a, 0x09, 0x61, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x5f, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x41,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x5f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x42, 0x22, 0x36, 0x0a, 0x0a, 0x61, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x72, 0x65, 0x73, 0x5f, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x73, 0x41, 0x12, 0x13, 0x0a, 0x05,
	0x72, 0x65, 0x73, 0x5f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x72, 0x65, 0x73,
	0x42, 0x32, 0x46, 0x0a, 0x0d, 0x41, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x47, 0x65, 0x74, 0x41, 0x12, 0x14, 0x2e, 0x61, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x70, 0x62, 0x2e, 0x61, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x70, 0x62, 0x2e, 0x61, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x61,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_a_proto_proto_rawDescOnce sync.Once
	file_a_proto_proto_rawDescData = file_a_proto_proto_rawDesc
)

func file_a_proto_proto_rawDescGZIP() []byte {
	file_a_proto_proto_rawDescOnce.Do(func() {
		file_a_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_a_proto_proto_rawDescData)
	})
	return file_a_proto_proto_rawDescData
}

var file_a_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_a_proto_proto_goTypes = []interface{}{
	(*ARequest)(nil),  // 0: a_protopb.a_request
	(*AResponse)(nil), // 1: a_protopb.a_response
}
var file_a_proto_proto_depIdxs = []int32{
	0, // 0: a_protopb.AMicroservice.GetA:input_type -> a_protopb.a_request
	1, // 1: a_protopb.AMicroservice.GetA:output_type -> a_protopb.a_response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_a_proto_proto_init() }
func file_a_proto_proto_init() {
	if File_a_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_a_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ARequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_a_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_a_proto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_a_proto_proto_goTypes,
		DependencyIndexes: file_a_proto_proto_depIdxs,
		MessageInfos:      file_a_proto_proto_msgTypes,
	}.Build()
	File_a_proto_proto = out.File
	file_a_proto_proto_rawDesc = nil
	file_a_proto_proto_goTypes = nil
	file_a_proto_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AMicroserviceClient is the client API for AMicroservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AMicroserviceClient interface {
	GetA(ctx context.Context, in *ARequest, opts ...grpc.CallOption) (*AResponse, error)
}

type aMicroserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewAMicroserviceClient(cc grpc.ClientConnInterface) AMicroserviceClient {
	return &aMicroserviceClient{cc}
}

func (c *aMicroserviceClient) GetA(ctx context.Context, in *ARequest, opts ...grpc.CallOption) (*AResponse, error) {
	out := new(AResponse)
	err := c.cc.Invoke(ctx, "/a_protopb.AMicroservice/GetA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AMicroserviceServer is the server API for AMicroservice service.
type AMicroserviceServer interface {
	GetA(context.Context, *ARequest) (*AResponse, error)
}

// UnimplementedAMicroserviceServer can be embedded to have forward compatible implementations.
type UnimplementedAMicroserviceServer struct {
}

func (*UnimplementedAMicroserviceServer) GetA(context.Context, *ARequest) (*AResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetA not implemented")
}

func RegisterAMicroserviceServer(s *grpc.Server, srv AMicroserviceServer) {
	s.RegisterService(&_AMicroservice_serviceDesc, srv)
}

func _AMicroservice_GetA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AMicroserviceServer).GetA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/a_protopb.AMicroservice/GetA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AMicroserviceServer).GetA(ctx, req.(*ARequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AMicroservice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "a_protopb.AMicroservice",
	HandlerType: (*AMicroserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetA",
			Handler:    _AMicroservice_GetA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a_proto.proto",
}
